web:
  image: lavoweb/php-7.4:latest
  ports:
    - "80:80"
  volumes:
    - ./www:/var/www/html/
  links:
    - dbserv:dbserv

dbserv:
  image: mysql:latest
  volumes:
    - ./mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=test
